### ISSUE TITLE
Nem indul.

### ISSUE THREAD

**Issue by JustforFunRSN** [balassy/MMM-Elvira#3]
Szia!
Sajnos nem tudjuk működésre bírni.

config: 
	{
      module: "MMM-Elvira",
      position: "top_right",
      header: 'Győr - Kelenföld',
      config: {
        startStationCode: '005501289',
        endStationCode: '005501024',
        updateInterval: 60000,
        headText: 'Győr - Kelenföld',
        showHead: true,
        showSymbolInHead: true,
        maxNumberOfItems: 10
      }
    },

indításkor:

[ERROR] (node:3597) UnhandledPromiseRejectionWarning: Error: Cannot find module 'request'
Require stack:
- /home/pi/MagicMirror/modules/MMM-Elvira/node_helper.js
- /home/pi/MagicMirror/js/app.js
- /home/pi/MagicMirror/js/electron.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1232:15)
    at s._resolveFilename (node:electron/js2c/browser_init:2:121498)
    at Module._resolveFilename (/home/pi/MagicMirror/node_modules/module-alias/index.js:49:29)
    at Module._load (node:internal/modules/cjs/loader:1058:27)
    at c._load (node:electron/js2c/node_init:2:17025)
    at Module.require (node:internal/modules/cjs/loader:1318:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Elvira/node_helper.js:2:17)
    at Module._compile (node:internal/modules/cjs/loader:1484:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1564:10)
    at Module.load (node:internal/modules/cjs/loader:1295:32)
    at Module._load (node:internal/modules/cjs/loader:1111:12)
    at c._load (node:electron/js2c/node_init:2:17025)
    at Module.require (node:internal/modules/cjs/loader:1318:19)
    at require (node:internal/modules/helpers:179:18)
    at loadModule (/home/pi/MagicMirror/js/app.js:200:19)
(Use `electron --trace-warnings ...` to show where the warning was created)
[2024-11-08 14:10:17.108] [ERROR] (node:3597) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)

**Comment by balassy** [comment]
Szia!
Én ezt a modult a MagicMirror egy régi verziójával használom, ott működik rendesen. Úgy tudom, hogy időközben a `request` nevű npm package már nem alap tartozéka a MagicMirrornak, ennek a modulnak viszont szüksége van rá. Ha a `modules\MMM-Elvira` mappában kiadod az `npm install request` parancsot és újraindítod a MagicMirrort, nem gyógyul meg?

**Comment by JustforFunRSN** [comment]
Szia!
De meggyógyult!
Nagyon szépen köszönöm a segítséget!

**Comment by balassy** [comment]
Nagyon örülök, köszi a visszajelzést, remélem elégedett leszel a modullal.
